LEIA: NarrowBand Class Reference
NarrowBand Class Reference
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
Public Member Functions
TypeName ("none")
declareRunTimeSelectionTable (autoPtr, NarrowBand, Dictionary,(const dictionary &dict, const volScalarField &psi),(dict, psi))
NarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~NarrowBand ()=default
const fvMesh & mesh () const
const volScalarField & psi () const
virtual void calc ()
virtual void write () const
Static Public Member Functions
static autoPtr< NarrowBand > New (const fvMesh &mesh, const volScalarField &psi)
Protected Attributes
const fvMesh & mesh_
const volScalarField & psi_
Detailed Description
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
Source files
NarrowBand.H
NarrowBand.C
Definition at line 52 of file NarrowBand.H.
Constructor & Destructor Documentation
NarrowBand()
NarrowBand (const dictionary & dict, const volScalarField & psi)
Definition at line 30 of file NarrowBand.C.
~NarrowBand()
virtual ~NarrowBand () virtual default
Member Function Documentation
TypeName()
TypeName ("none")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , NarrowBand , Dictionary , (const dictionary &dict, const volScalarField &psi) , (dict, psi))
New()
autoPtr< NarrowBand > New (const fvMesh & mesh, const volScalarField & psi) static
Definition at line 37 of file NarrowBand.C.
References NarrowBand::mesh(), and NarrowBand::psi().
mesh()
const fvMesh & mesh () const
Definition at line 63 of file NarrowBand.C.
References NarrowBand::mesh_.
Referenced by DistanceNarrowBand::calc(), NeighbourNarrowBand::calc(), SignChangeNarrowBand::calc(), and NarrowBand::New().
psi()
const volScalarField & psi () const
Definition at line 68 of file NarrowBand.C.
References NarrowBand::psi_.
Referenced by DistanceNarrowBand::calc(), SignChangeNarrowBand::calc(), and NarrowBand::New().
calc()
void calc () virtual
Reimplemented in SignChangeNarrowBand, NeighbourNarrowBand, and DistanceNarrowBand.
Definition at line 73 of file NarrowBand.C.
write()
void write () const virtual
Reimplemented in EmptyNarrowBand.
Definition at line 76 of file NarrowBand.C.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 55 of file NarrowBand.H.
Referenced by NarrowBand::mesh().
psi_
const volScalarField& psi_ protected
Definition at line 56 of file NarrowBand.H.
Referenced by NarrowBand::psi().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/NarrowBand.H
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/NarrowBand.C