LEIA: EmptyNarrowBand Class Reference
EmptyNarrowBand Class Reference
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
Public Member Functions
TypeName ("empty")
EmptyNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~EmptyNarrowBand ()=default
const volScalarField & field () const
volScalarField & field ()
virtual void write () const
Public Member Functions inherited from NarrowBand
TypeName ("none")
declareRunTimeSelectionTable (autoPtr, NarrowBand, Dictionary,(const dictionary &dict, const volScalarField &psi),(dict, psi))
NarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~NarrowBand ()=default
const fvMesh & mesh () const
const volScalarField & psi () const
virtual void calc ()
Private Attributes
volScalarField field_
Additional Inherited Members
Static Public Member Functions inherited from NarrowBand
static autoPtr< NarrowBand > New (const fvMesh &mesh, const volScalarField &psi)
Protected Attributes inherited from NarrowBand
const fvMesh & mesh_
const volScalarField & psi_
Detailed Description
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
Source files
EmptyNarrowBand.H
EmptyNarrowBand.C
Definition at line 49 of file EmptyNarrowBand.H.
Constructor & Destructor Documentation
EmptyNarrowBand()
EmptyNarrowBand (const dictionary & dict, const volScalarField & psi)
Definition at line 29 of file EmptyNarrowBand.C.
~EmptyNarrowBand()
virtual ~EmptyNarrowBand () virtual default
Member Function Documentation
TypeName()
TypeName ("empty")
field() [1/2]
const volScalarField & field () const
Definition at line 45 of file EmptyNarrowBand.C.
References EmptyNarrowBand::field_.
Referenced by DistanceNarrowBand::calc(), NeighbourNarrowBand::calc(), SignChangeNarrowBand::calc(), and EmptyNarrowBand::write().
field() [2/2]
volScalarField & field ()
Definition at line 50 of file EmptyNarrowBand.C.
References EmptyNarrowBand::field_.
write()
void write () const virtual
Reimplemented from NarrowBand.
Definition at line 55 of file EmptyNarrowBand.C.
References EmptyNarrowBand::field().
Member Data Documentation
field_
volScalarField field_ private
Definition at line 53 of file EmptyNarrowBand.H.
Referenced by EmptyNarrowBand::field().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/EmptyNarrowBand.H
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/EmptyNarrowBand.C