LEIA: /home/julian/OpenFOAM/leia2/applications/test/leiaTestLevelSet/leiaTestLevelSet.C File Reference
leiaTestLevelSet.C File Reference
TODO.
Functions
void redistancedPlaneIsUnchanged (autoPtr< redistancer > &redist, const fvMesh &mesh)
void phaseIndicatorIsBounded (autoPtr< phaseIndicator > &phaseInd, const fvMesh &mesh)
int main (int argc, char *argv[])
Detailed Description
TODO.
Original source file leiaTestLevelSet.C
Definition in file leiaTestLevelSet.C.
Function Documentation
redistancedPlaneIsUnchanged()
void redistancedPlaneIsUnchanged (autoPtr< redistancer > & redist, const fvMesh & mesh)
Definition at line 33 of file leiaTestLevelSet.C.
References psi0(), and redist.
Referenced by main().
phaseIndicatorIsBounded()
void phaseIndicatorIsBounded (autoPtr< phaseIndicator > & phaseInd, const fvMesh & mesh)
Definition at line 153 of file leiaTestLevelSet.C.
References phaseInd.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 191 of file leiaTestLevelSet.C.
References phaseInd, phaseIndicatorIsBounded(), redist, and redistancedPlaneIsUnchanged().