LEIA: SDPLSSource Class Reference
SDPLSSource Class Reference
The base class SDPLSSource is the root for the model hierarchy of the SDPLS method by Fricke et. al. [1]. It is the only class with which the user of the SDPLS method should interact. The SDPLS method extends the standard LS advection equation with the SDPLS source term. This is done by extending the r.h.s. of the LS equation in the solver application by calling.
Public Member Functions
TypeName ("noSource")
declareRunTimeSelectionTable (autoPtr, SDPLSSource, Dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
SDPLSSource (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~SDPLSSource ()=default
Destructor.
tmp< fvScalarMatrix > fvmSDPLSSource (const volScalarField &psi, const volVectorField &U)
void update (const volScalarField &psi, const volVectorField &U)
void write () const
Static Public Member Functions
static autoPtr< SDPLSSource > New (const fvMesh &mesh)
Select default constructed.
Protected Member Functions
virtual tmp< volScalarField > nonLinearPart (const volScalarField &R, const volScalarField &psi, const volVectorField &U) const
tmp< volVectorField > gradPsi (const volScalarField &psi) const
Private Member Functions
tmp< volScalarField > R (const volScalarField &psi, const volVectorField &U) const
Private Attributes
autoPtr< SourceScheme > discretization_
autoPtr< GradPsi > gradPsi_
autoPtr< Mollifier > mollifier_
volScalarField R_
volScalarField nonLinearPart_
Detailed Description
The base class SDPLSSource is the root for the model hierarchy of the SDPLS method by Fricke et. al. [1]. It is the only class with which the user of the SDPLS method should interact. The SDPLS method extends the standard LS advection equation with the SDPLS source term. This is done by extending the r.h.s. of the LS equation in the solver application by calling.
fvmSDPLSSource(const volScalarField& psi, const volVectorField& U)
on the RTS selected model and passing a reference to the LS field psi and the velocity field U. It returns a tmp<fvScalarMatrix> object for integration into the LS equation. This class hierarchy is responsible for providing implementations for the formula of non-linear SDPLS source terms. It is assumed that all SDPLS source term variants have the following structure and evaluate the source in cell as
with the solution field at time , some non-linear scalar function and the solution value in cell . All inherited classes are responsible for implementing this non-linear function by overloading the member function nonLinearPart(). This base class implements the case of an inactive source term. The discretization is done separately by the class hierarchy SourceScheme, which is related via the strategy pattern. Furthermore, this class has a strategy for a Mollifier, which restricts the active source term to a narrow band around the interface.
Source files
SDPLSSource.H
SDPLSSource.C
Definition at line 83 of file SDPLSSource.H.
Constructor & Destructor Documentation
SDPLSSource()
SDPLSSource (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 67 of file SDPLSSource.C.
~SDPLSSource()
virtual ~SDPLSSource () virtual default
Destructor.
Member Function Documentation
TypeName()
TypeName ("noSource")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , SDPLSSource , Dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
New()
Foam::autoPtr< SDPLSSource > New (const fvMesh & mesh) static
Select default constructed.
Definition at line 40 of file SDPLSSource.C.
Referenced by Foam::fvm::SDPLSSource().
fvmSDPLSSource()
tmp< fvScalarMatrix > fvmSDPLSSource (const volScalarField & psi, const volVectorField & U)
Definition at line 99 of file SDPLSSource.C.
References SDPLSSource::discretization_, SDPLSSource::mollifier_, SDPLSSource::nonLinearPart_, and SDPLSSource::update().
update()
void update (const volScalarField & psi, const volVectorField & U)
Definition at line 117 of file SDPLSSource.C.
References SDPLSSource::nonLinearPart(), SDPLSSource::nonLinearPart_, SDPLSSource::R(), and SDPLSSource::R_.
Referenced by SDPLSSource::fvmSDPLSSource().
write()
void write () const
Definition at line 162 of file SDPLSSource.C.
References SDPLSSource::nonLinearPart_, and SDPLSSource::R_.
nonLinearPart()
tmp< volScalarField > nonLinearPart (const volScalarField & R, const volScalarField & psi, const volVectorField & U) const protected virtual
Reimplemented in SDPLS_test, SDPLS_Rquad, SDPLS_Rlin, SDPLS_R, SDPLS_quad, and SDPLS_lin.
Definition at line 140 of file SDPLSSource.C.
References SDPLSSource::nonLinearPart_.
Referenced by SDPLSSource::update().
gradPsi()
tmp< volVectorField > gradPsi (const volScalarField & psi) const protected
Definition at line 135 of file SDPLSSource.C.
References SDPLSSource::gradPsi_.
Referenced by SDPLS_lin::nonLinearPart(), SDPLS_quad::nonLinearPart(), SDPLS_Rlin::nonLinearPart(), SDPLS_Rquad::nonLinearPart(), and SDPLSSource::R().
R()
tmp< volScalarField > R (const volScalarField & psi, const volVectorField & U) const private
Definition at line 125 of file SDPLSSource.C.
References SDPLSSource::gradPsi().
Referenced by SDPLS_R::nonLinearPart(), SDPLS_Rlin::nonLinearPart(), SDPLS_Rquad::nonLinearPart(), and SDPLSSource::update().
Member Data Documentation
discretization_
autoPtr<SourceScheme> discretization_ private
Definition at line 87 of file SDPLSSource.H.
Referenced by SDPLSSource::fvmSDPLSSource().
gradPsi_
autoPtr<GradPsi> gradPsi_ private
Definition at line 88 of file SDPLSSource.H.
Referenced by SDPLSSource::gradPsi().
mollifier_
autoPtr<Mollifier> mollifier_ private
Definition at line 89 of file SDPLSSource.H.
Referenced by SDPLSSource::fvmSDPLSSource().
R_
volScalarField R_ private
Definition at line 96 of file SDPLSSource.H.
Referenced by SDPLSSource::update(), and SDPLSSource::write().
nonLinearPart_
volScalarField nonLinearPart_ private
Definition at line 97 of file SDPLSSource.H.
Referenced by SDPLSSource::fvmSDPLSSource(), SDPLSSource::nonLinearPart(), SDPLSSource::update(), and SDPLSSource::write().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/SDPLSSource/SDPLSSource.H
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/SDPLSSource/SDPLSSource.C