LEIA: implicitEllipsoid Class Reference
implicitEllipsoid Class Reference
Public Member Functions
TypeName ("implicitEllipsoid")
implicitEllipsoid (vector center, vector axes)
implicitEllipsoid (const dictionary &dict)
virtual ~implicitEllipsoid ()=default
virtual scalar value (const vector &x) const
virtual vector grad (const vector &x) const
virtual scalar curvature (const vector &x) const
vector center () const
vector axes () const
Public Member Functions inherited from implicitSurface
TypeName ("implicitSurface")
declareRunTimeSelectionTable (autoPtr, implicitSurface, dictionary,(const dictionary &dict),(dict))
implicitSurface ()=default
implicitSurface (const dictionary &dict)
virtual ~implicitSurface ()=default
Private Member Functions
void setAxesSqr (const vector &axes)
Private Attributes
vector center_
vector axes_
vector axesSqr_
Additional Inherited Members
Static Public Member Functions inherited from implicitSurface
static autoPtr< implicitSurface > New (const word &name, const dictionary &dict)
Detailed Description
Definition at line 194 of file levelSetImplicitSurfaces.H.
Constructor & Destructor Documentation
implicitEllipsoid() [1/2]
implicitEllipsoid (vector center, vector axes)
Definition at line 309 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axes(), and implicitEllipsoid::setAxesSqr().
implicitEllipsoid() [2/2]
implicitEllipsoid (const dictionary & dict)
Definition at line 317 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axes_, and implicitEllipsoid::setAxesSqr().
~implicitEllipsoid()
virtual ~implicitEllipsoid () virtual default
Member Function Documentation
setAxesSqr()
void setAxesSqr (const vector & axes) private
Definition at line 327 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axes(), and implicitEllipsoid::axesSqr_.
Referenced by implicitEllipsoid::implicitEllipsoid().
TypeName()
TypeName ("implicitEllipsoid")
value()
scalar value (const vector & x) const virtual
Implements implicitSurface.
Definition at line 334 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axesSqr_, and implicitEllipsoid::center_.
grad()
vector grad (const vector & x) const virtual
Implements implicitSurface.
Definition at line 341 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axesSqr_, and implicitEllipsoid::center_.
curvature()
scalar curvature (const vector & x) const virtual
Implements implicitSurface.
Definition at line 361 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axesSqr_, and implicitEllipsoid::center_.
center()
vector center () const
Definition at line 351 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::center_.
axes()
vector axes () const
Definition at line 356 of file levelSetImplicitSurfaces.C.
References implicitEllipsoid::axes_.
Referenced by implicitEllipsoid::implicitEllipsoid(), and implicitEllipsoid::setAxesSqr().
Member Data Documentation
center_
vector center_ private
Definition at line 196 of file levelSetImplicitSurfaces.H.
Referenced by implicitEllipsoid::center(), implicitEllipsoid::curvature(), implicitEllipsoid::grad(), and implicitEllipsoid::value().
axes_
vector axes_ private
Definition at line 197 of file levelSetImplicitSurfaces.H.
Referenced by implicitEllipsoid::axes(), and implicitEllipsoid::implicitEllipsoid().
axesSqr_
vector axesSqr_ private
Definition at line 198 of file levelSetImplicitSurfaces.H.
Referenced by implicitEllipsoid::curvature(), implicitEllipsoid::grad(), implicitEllipsoid::setAxesSqr(), and implicitEllipsoid::value().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/levelSetImplicitSurfaces/levelSetImplicitSurfaces.H
/home/julian/OpenFOAM/leia2/src/levelSetImplicitSurfaces/levelSetImplicitSurfaces.C