LEIA: explicitMag1GradientFvPatchField Class Reference
explicitMag1GradientFvPatchField Class Reference
Sets the BC gradient to the normalized gradient of the internalField of the last time step.
Public Member Functions
TypeName ("explicitMag1Gradient")
Runtime type information.
explicitMag1GradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
explicitMag1GradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given explicitMag1GradientFvPatchField.
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField &)
Construct as copy.
virtual tmp< fvPatchField< scalar > > clone () const
Construct and return a clone.
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< Field< vector > > calcGradient ()
Public Member Functions inherited from explicitGradientFvPatchField
TypeName ("explicitGradient")
Runtime type information.
explicitGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
explicitGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
explicitGradientFvPatchField (const explicitGradientFvPatchField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given explicitGradientFvPatchField.
explicitGradientFvPatchField (const explicitGradientFvPatchField &)
Construct as copy.
explicitGradientFvPatchField (const explicitGradientFvPatchField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< Field< scalar > > snGrad () const
Return gradient at boundary.
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Evaluate the patch field.
virtual void write (Ostream &os) const
Detailed Description
Sets the BC gradient to the normalized gradient of the internalField of the last time step.
$\nabla \psi_b^{n+1} = \frac{\nabla \psi_c^{n}}{|\nabla \psi_c^{n}|} $
where
= gradient (user-specified)
Usage
Example of the boundary condition specification:
<patchName>
{
    type            explicitMag1Gradient;
}
Source files
explicitMag1GradientFvPatchField.H
explicitMag1GradientFvPatchField.C
Definition at line 72 of file explicitMag1GradientFvPatchField.H.
Constructor & Destructor Documentation
explicitMag1GradientFvPatchField() [1/5]
explicitMag1GradientFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 29 of file explicitMag1GradientFvPatchField.C.
Referenced by explicitMag1GradientFvPatchField::clone().
explicitMag1GradientFvPatchField() [2/5]
explicitMag1GradientFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 40 of file explicitMag1GradientFvPatchField.C.
explicitMag1GradientFvPatchField() [3/5]
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given explicitMag1GradientFvPatchField.
onto a new patch
Definition at line 52 of file explicitMag1GradientFvPatchField.C.
explicitMag1GradientFvPatchField() [4/5]
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField & ptf)
Construct as copy.
Definition at line 65 of file explicitMag1GradientFvPatchField.C.
explicitMag1GradientFvPatchField() [5/5]
explicitMag1GradientFvPatchField (const explicitMag1GradientFvPatchField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 75 of file explicitMag1GradientFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("explicitMag1Gradient")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchField<scalar> > clone () const inline virtual
Construct and return a clone.
Reimplemented from explicitGradientFvPatchField.
Definition at line 132 of file explicitMag1GradientFvPatchField.H.
References explicitMag1GradientFvPatchField::explicitMag1GradientFvPatchField().
clone() [2/2]
virtual tmp<fvPatchField<scalar> > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from explicitGradientFvPatchField.
Definition at line 152 of file explicitMag1GradientFvPatchField.H.
References explicitMag1GradientFvPatchField::explicitMag1GradientFvPatchField().
calcGradient()
tmp< Field< vector > > calcGradient () virtual
Reimplemented from explicitGradientFvPatchField.
Definition at line 87 of file explicitMag1GradientFvPatchField.C.
References explicitGradientFvPatchField::calcGradient().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/finiteVolume/fields/fvPatchFields/derived/explicitMag1Gradient/explicitMag1GradientFvPatchField.H
/home/julian/OpenFOAM/leia2/src/finiteVolume/fields/fvPatchFields/derived/explicitMag1Gradient/explicitMag1GradientFvPatchField.C