LEIA: /home/julian/OpenFOAM/leia2/applications/test/leiaTestFoamGeometry/leiaTestFoamGeometry.C File Reference
leiaTestFoamGeometry.C File Reference
Functions
void testTriangleArea ()
void testOrientedSquareArea ()
void testUnorientedSquareArea ()
void testVolFraction_UnitDomainInsidePlaneHalfspace (volScalarField &alpha)
void testVolFraction_UnitDomainHalved (volScalarField &alpha)
void testVolFraction_UnitDomainTranslatingPlane (volScalarField &alpha, Time &runTime)
int main (int argc, char *argv[])
Detailed Description
Original source file leiaTestFoamGeometry.C
Definition in file leiaTestFoamGeometry.C.
Function Documentation
testTriangleArea()
void testTriangleArea ()
Definition at line 42 of file leiaTestFoamGeometry.C.
References Foam::centroid(), Foam::centroidAreaNormal(), Foam::normalArea(), and Foam::orientedAreaNormal().
Referenced by main().
testOrientedSquareArea()
void testOrientedSquareArea ()
Definition at line 79 of file leiaTestFoamGeometry.C.
References Foam::centroid(), Foam::centroidAreaNormal(), Foam::normalArea(), and Foam::orientedAreaNormal().
Referenced by main().
testUnorientedSquareArea()
void testUnorientedSquareArea ()
Definition at line 117 of file leiaTestFoamGeometry.C.
References Foam::centroid(), Foam::centroidAreaNormal(), and Foam::normalArea().
Referenced by main().
testVolFraction_UnitDomainInsidePlaneHalfspace()
void testVolFraction_UnitDomainInsidePlaneHalfspace (volScalarField & alpha)
Definition at line 150 of file leiaTestFoamGeometry.C.
References Foam::intersectCell().
testVolFraction_UnitDomainHalved()
void testVolFraction_UnitDomainHalved (volScalarField & alpha)
Definition at line 203 of file leiaTestFoamGeometry.C.
References Foam::intersectCell().
Referenced by main().
testVolFraction_UnitDomainTranslatingPlane()
void testVolFraction_UnitDomainTranslatingPlane (volScalarField & alpha, Time & runTime)
Definition at line 329 of file leiaTestFoamGeometry.C.
References Foam::intersectCell().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 399 of file leiaTestFoamGeometry.C.
References testOrientedSquareArea(), testTriangleArea(), testUnorientedSquareArea(), testVolFraction_UnitDomainHalved(), and testVolFraction_UnitDomainTranslatingPlane().