var annotated_dup =
[
    [ "Foam", "namespaceFoam.html", [
      [ "functionObjects", "namespaceFoam_1_1functionObjects.html", [
        [ "gradPsiError", "classFoam_1_1functionObjects_1_1gradPsiError.html", "classFoam_1_1functionObjects_1_1gradPsiError" ],
        [ "gradPsiErrorCSV", "classFoam_1_1functionObjects_1_1gradPsiErrorCSV.html", "classFoam_1_1functionObjects_1_1gradPsiErrorCSV" ],
        [ "TVerrorCSV", "classFoam_1_1functionObjects_1_1TVerrorCSV.html", "classFoam_1_1functionObjects_1_1TVerrorCSV" ]
      ] ],
      [ "explicitGradientFvPatchField", "classFoam_1_1explicitGradientFvPatchField.html", "classFoam_1_1explicitGradientFvPatchField" ],
      [ "explicitMag1GradientFvPatchField", "classFoam_1_1explicitMag1GradientFvPatchField.html", "classFoam_1_1explicitMag1GradientFvPatchField" ],
      [ "writeIsoSurfaceTopoFunctionObject", "classFoam_1_1writeIsoSurfaceTopoFunctionObject.html", "classFoam_1_1writeIsoSurfaceTopoFunctionObject" ],
      [ "DistanceNarrowBand", "classFoam_1_1DistanceNarrowBand.html", "classFoam_1_1DistanceNarrowBand" ],
      [ "EmptyNarrowBand", "classFoam_1_1EmptyNarrowBand.html", "classFoam_1_1EmptyNarrowBand" ],
      [ "NarrowBand", "classFoam_1_1NarrowBand.html", "classFoam_1_1NarrowBand" ],
      [ "NeighbourNarrowBand", "classFoam_1_1NeighbourNarrowBand.html", "classFoam_1_1NeighbourNarrowBand" ],
      [ "SignChangeNarrowBand", "classFoam_1_1SignChangeNarrowBand.html", "classFoam_1_1SignChangeNarrowBand" ],
      [ "geometricPhaseIndicator", "classFoam_1_1geometricPhaseIndicator.html", "classFoam_1_1geometricPhaseIndicator" ],
      [ "heavisidePhaseIndicator", "classFoam_1_1heavisidePhaseIndicator.html", "classFoam_1_1heavisidePhaseIndicator" ],
      [ "phaseIndicator", "classFoam_1_1phaseIndicator.html", "classFoam_1_1phaseIndicator" ],
      [ "sharpJumpPhaseIndicator", "classFoam_1_1sharpJumpPhaseIndicator.html", "classFoam_1_1sharpJumpPhaseIndicator" ],
      [ "profile", "classFoam_1_1profile.html", "classFoam_1_1profile" ],
      [ "signedDistance", "classFoam_1_1signedDistance.html", "classFoam_1_1signedDistance" ],
      [ "tanhProfile", "classFoam_1_1tanhProfile.html", "classFoam_1_1tanhProfile" ],
      [ "lsqRedistancer", "classFoam_1_1lsqRedistancer.html", "classFoam_1_1lsqRedistancer" ],
      [ "redistancer", "classFoam_1_1redistancer.html", "classFoam_1_1redistancer" ],
      [ "GradPsi", "classFoam_1_1GradPsi.html", "classFoam_1_1GradPsi" ],
      [ "NarrowLS", "classFoam_1_1NarrowLS.html", "classFoam_1_1NarrowLS" ],
      [ "Mollifier", "classFoam_1_1Mollifier.html", "classFoam_1_1Mollifier" ],
      [ "Mollifier1", "classFoam_1_1Mollifier1.html", "classFoam_1_1Mollifier1" ],
      [ "SDPLS_lin", "classFoam_1_1SDPLS__lin.html", "classFoam_1_1SDPLS__lin" ],
      [ "SDPLS_quad", "classFoam_1_1SDPLS__quad.html", "classFoam_1_1SDPLS__quad" ],
      [ "SDPLS_R", "classFoam_1_1SDPLS__R.html", "classFoam_1_1SDPLS__R" ],
      [ "SDPLS_Rlin", "classFoam_1_1SDPLS__Rlin.html", "classFoam_1_1SDPLS__Rlin" ],
      [ "SDPLS_Rquad", "classFoam_1_1SDPLS__Rquad.html", "classFoam_1_1SDPLS__Rquad" ],
      [ "SDPLSSource", "classFoam_1_1SDPLSSource.html", "classFoam_1_1SDPLSSource" ],
      [ "explicitScheme", "classFoam_1_1explicitScheme.html", "classFoam_1_1explicitScheme" ],
      [ "simpleLinearImplicitScheme", "classFoam_1_1simpleLinearImplicitScheme.html", "classFoam_1_1simpleLinearImplicitScheme" ],
      [ "SourceScheme", "classFoam_1_1SourceScheme.html", "classFoam_1_1SourceScheme" ],
      [ "strictNegativeSpLinearImplicitScheme", "classFoam_1_1strictNegativeSpLinearImplicitScheme.html", "classFoam_1_1strictNegativeSpLinearImplicitScheme" ],
      [ "implicitSurface", "classFoam_1_1implicitSurface.html", "classFoam_1_1implicitSurface" ],
      [ "implicitPlane", "classFoam_1_1implicitPlane.html", "classFoam_1_1implicitPlane" ],
      [ "hesseNormalPlane", "classFoam_1_1hesseNormalPlane.html", "classFoam_1_1hesseNormalPlane" ],
      [ "implicitSphere", "classFoam_1_1implicitSphere.html", "classFoam_1_1implicitSphere" ],
      [ "implicitSlottedSphere", "classFoam_1_1implicitSlottedSphere.html", "classFoam_1_1implicitSlottedSphere" ],
      [ "implicitEllipsoid", "classFoam_1_1implicitEllipsoid.html", "classFoam_1_1implicitEllipsoid" ],
      [ "implicitSinc", "classFoam_1_1implicitSinc.html", "classFoam_1_1implicitSinc" ],
      [ "volumeArea", "structFoam_1_1volumeArea.html", "structFoam_1_1volumeArea" ],
      [ "velocityModel", "classFoam_1_1velocityModel.html", "classFoam_1_1velocityModel" ],
      [ "shear2D", "classFoam_1_1shear2D.html", "classFoam_1_1shear2D" ],
      [ "deformation3D", "classFoam_1_1deformation3D.html", "classFoam_1_1deformation3D" ],
      [ "shear3D", "classFoam_1_1shear3D.html", "classFoam_1_1shear3D" ],
      [ "translation", "classFoam_1_1translation.html", "classFoam_1_1translation" ],
      [ "rotation", "classFoam_1_1rotation.html", "classFoam_1_1rotation" ],
      [ "vortex2D", "classFoam_1_1vortex2D.html", "classFoam_1_1vortex2D" ],
      [ "periodic2D", "classFoam_1_1periodic2D.html", "classFoam_1_1periodic2D" ]
    ] ],
    [ "dictionaryContent", "classdictionaryContent.html", null ],
    [ "fieldExpression", "classfieldExpression.html", null ],
    [ "fvMeshFunctionObject", "classfvMeshFunctionObject.html", null ],
    [ "fvPatchField", "classfvPatchField.html", null ],
    [ "GradPsi1", "classFoam_1_1GradPsi1.html", null ],
    [ "Mollifier11", "classFoam_1_1Mollifier11.html", null ],
    [ "NarrowLS1", "classFoam_1_1NarrowLS1.html", null ]
];