LEIA: writeIsoSurfaceTopoFunctionObject Class Reference
writeIsoSurfaceTopoFunctionObject Class Reference
Public Member Functions
TypeName ("writeIsoSurfaceTopo")
Runtime type information.
writeIsoSurfaceTopoFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~writeIsoSurfaceTopoFunctionObject ()
Destructor.
const dictionary & codeContext () const noexcept
Code context as a dictionary.
virtual bool read (const dictionary &dict)
Read optional controls.
virtual bool execute ()
Execute (at time-step)
virtual bool write ()
Write (at write interval)
virtual bool end ()
Executed at the final time-loop.
Private Member Functions
const fvMesh & mesh () const
Cast reference of objectRegistry to fvMesh.
writeIsoSurfaceTopoFunctionObject (const writeIsoSurfaceTopoFunctionObject &)=delete
No copy construct.
void operator= (const writeIsoSurfaceTopoFunctionObject &)=delete
No copy assignment.
Detailed Description
Definition at line 85 of file writeIsoSurfaceTopo.H.
Constructor & Destructor Documentation
writeIsoSurfaceTopoFunctionObject() [1/2]
writeIsoSurfaceTopoFunctionObject (const writeIsoSurfaceTopoFunctionObject &) private delete
No copy construct.
writeIsoSurfaceTopoFunctionObject() [2/2]
writeIsoSurfaceTopoFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 58 of file writeIsoSurfaceTopo.C.
References writeIsoSurfaceTopoFunctionObject::read().
~writeIsoSurfaceTopoFunctionObject()
~writeIsoSurfaceTopoFunctionObject () virtual
Destructor.
Definition at line 74 of file writeIsoSurfaceTopo.C.
Member Function Documentation
mesh()
const Foam::fvMesh & mesh () const private
Cast reference of objectRegistry to fvMesh.
Definition at line 50 of file writeIsoSurfaceTopo.C.
operator=()
void operator= (const writeIsoSurfaceTopoFunctionObject &) private delete
No copy assignment.
TypeName()
TypeName ("writeIsoSurfaceTopo")
Runtime type information.
codeContext()
const dictionary& codeContext () const inline noexcept
Code context as a dictionary.
Definition at line 144 of file writeIsoSurfaceTopo.H.
read()
bool read (const dictionary & dict) virtual
Read optional controls.
Definition at line 79 of file writeIsoSurfaceTopo.C.
References Foam::writeIsoSurfaceTopo().
Referenced by writeIsoSurfaceTopoFunctionObject::writeIsoSurfaceTopoFunctionObject().
execute()
bool execute () virtual
Execute (at time-step)
Definition at line 87 of file writeIsoSurfaceTopo.C.
References Foam::writeIsoSurfaceTopo().
write()
bool write () virtual
Write (at write interval)
Definition at line 95 of file writeIsoSurfaceTopo.C.
end()
bool end () virtual
Executed at the final time-loop.
Definition at line 101 of file writeIsoSurfaceTopo.C.
References Foam::writeIsoSurfaceTopo().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/functionObjects/writeIsoSurfaceTopo/writeIsoSurfaceTopo.H
/home/julian/OpenFOAM/leia2/src/functionObjects/writeIsoSurfaceTopo/writeIsoSurfaceTopo.C