LEIA: NeighbourNarrowBand Class Reference
NeighbourNarrowBand Class Reference
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
Public Member Functions
TypeName ("neighbours")
NeighbourNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~NeighbourNarrowBand ()=default
virtual void calc ()
Public Member Functions inherited from SignChangeNarrowBand
TypeName ("signChange")
SignChangeNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~SignChangeNarrowBand ()=default
Public Member Functions inherited from EmptyNarrowBand
TypeName ("empty")
EmptyNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~EmptyNarrowBand ()=default
const volScalarField & field () const
volScalarField & field ()
virtual void write () const
Public Member Functions inherited from NarrowBand
TypeName ("none")
declareRunTimeSelectionTable (autoPtr, NarrowBand, Dictionary,(const dictionary &dict, const volScalarField &psi),(dict, psi))
NarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~NarrowBand ()=default
const fvMesh & mesh () const
const volScalarField & psi () const
Private Attributes
int ntimes_
Additional Inherited Members
Static Public Member Functions inherited from NarrowBand
static autoPtr< NarrowBand > New (const fvMesh &mesh, const volScalarField &psi)
Protected Attributes inherited from NarrowBand
const fvMesh & mesh_
const volScalarField & psi_
Detailed Description
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
Source files
NeighbourNarrowBand.H
NeighbourNarrowBand.C
Definition at line 48 of file NeighbourNarrowBand.H.
Constructor & Destructor Documentation
NeighbourNarrowBand()
NeighbourNarrowBand (const dictionary & dict, const volScalarField & psi)
Definition at line 29 of file NeighbourNarrowBand.C.
~NeighbourNarrowBand()
virtual ~NeighbourNarrowBand () virtual default
Member Function Documentation
TypeName()
TypeName ("neighbours")
calc()
void calc () virtual
Reimplemented from SignChangeNarrowBand.
Definition at line 35 of file NeighbourNarrowBand.C.
References SignChangeNarrowBand::calc(), EmptyNarrowBand::field(), NarrowBand::mesh(), and NeighbourNarrowBand::ntimes_.
Member Data Documentation
ntimes_
int ntimes_ private
Definition at line 51 of file NeighbourNarrowBand.H.
Referenced by NeighbourNarrowBand::calc().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/NeighbourNarrowBand.H
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/NeighbourNarrowBand.C