LEIA: TVerrorCSV Class Reference
TVerrorCSV Class Reference
Calculates the TotalVaration of a field \psi and its absolute and relative error compared to the initial state. The calculates properties are written to a CSV file "TVerror.csv".
Public Member Functions
TypeName ("TVerrorCSV")
Runtime type information.
TVerrorCSV (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
TVerrorCSV (const TVerrorCSV &)=delete
No copy construct.
void operator= (const TVerrorCSV &)=delete
No copy assignment.
virtual bool execute ()
virtual bool write ()
virtual ~TVerrorCSV ()=default
Destructor.
Private Member Functions
scalar calcTV ()
Private Attributes
const volScalarField & field_
scalar TV_initial_
OFstream csvFile_
Detailed Description
Calculates the TotalVaration of a field \psi and its absolute and relative error compared to the initial state. The calculates properties are written to a CSV file "TVerror.csv".
<equation>
Usage
Minimal example by using system/controlDict.functions:
TVerrorCSV
{
    type            TVerrorCSV;
    libs            ( leiaFunctionObjects );
    writeControl    timeStep;
    field           psi;
}
The inherited entries are elaborated in:
functionObject.H
fieldExpression.H
fieldsExpression.H
writeFile.H ...
<if postProcess is applicable> Minimal example by using the postProcess utility:
    postProcess -func TVerrorCSV
<if postProcess is not applicable> Usage by the postProcess utility is not available.
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
ExtendedCodeGuide::functionObjects::field::TVerrorCSV ...
Source files
TVerrorCSV.H
TVerrorCSV.C
TVerrorCSVTEMPLATES.C
...
Definition at line 95 of file TVerrorCSV.H.
Constructor & Destructor Documentation
TVerrorCSV() [1/2]
TVerrorCSV (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 40 of file TVerrorCSV.C.
References TVerrorCSV::calcTV(), TVerrorCSV::csvFile_, TVerrorCSV::TV_initial_, and TVerrorCSV::write().
TVerrorCSV() [2/2]
TVerrorCSV (const TVerrorCSV &) delete
No copy construct.
~TVerrorCSV()
virtual ~TVerrorCSV () virtual default
Destructor.
Member Function Documentation
calcTV()
scalar calcTV () private
Definition at line 85 of file TVerrorCSV.C.
Referenced by TVerrorCSV::TVerrorCSV().
TypeName()
TypeName ("TVerrorCSV")
Runtime type information.
operator=()
void operator= (const TVerrorCSV &) delete
No copy assignment.
execute()
virtual bool execute () inline virtual
Definition at line 135 of file TVerrorCSV.H.
write()
bool write () virtual
Definition at line 66 of file TVerrorCSV.C.
Referenced by TVerrorCSV::TVerrorCSV().
Member Data Documentation
field_
const volScalarField& field_ private
Definition at line 100 of file TVerrorCSV.H.
TV_initial_
scalar TV_initial_ private
Definition at line 101 of file TVerrorCSV.H.
Referenced by TVerrorCSV::TVerrorCSV().
csvFile_
OFstream csvFile_ private
Definition at line 102 of file TVerrorCSV.H.
Referenced by TVerrorCSV::TVerrorCSV().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/functionObjects/TVerrorCSV/TVerrorCSV.H
/home/julian/OpenFOAM/leia2/src/functionObjects/TVerrorCSV/TVerrorCSV.C