LEIA: /home/julian/OpenFOAM/leia2/applications/solvers/leiaLevelSetFoam/createFields.H File Reference
createFields.H File Reference
Functions
narrowBand calc ()
narrowBand write ()
phaseInd calcPhaseIndicator (alpha, psi)
source update (psi, U)
velocityModel setVolumetricFlux (phi)
if (args.found("fluxCorrection")) correctFlux(phi)
velocityModel setVelocity (U)
Variables
Info<< "Reading field psi\n"<< endl;volScalarField psi(IOobject("psi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field alpha\n"<< endl;volScalarField alpha(IOobject("alpha", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field phi\n"<< endl;surfaceScalarField phi(IOobject("phi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("phi", dimVolume/dimTime, 0));Info<< "Initializing field U (visualization)\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector("U", dimVelocity, vector(0, 0, 0)));autoPtr< redistancer > redist = redistancer::New(mesh)
autoPtr< NarrowBand > narrowBand = NarrowBand::New(mesh, psi)
autoPtr< phaseIndicator > phaseInd = phaseIndicator::New(mesh)
autoPtr< SDPLSSource > source = SDPLSSource::New(mesh)
autoPtr< velocityModel > velocityModel = velocityModel::New(mesh)
Function Documentation
calc()
narrowBand calc ()
write()
U write ()
Referenced by gradPsiError::gradPsiError(), and explicitGradientFvPatchField::write().
calcPhaseIndicator()
phaseInd calcPhaseIndicator (alpha , psi)
update()
source update (psi , U)
setVolumetricFlux()
velocityModel setVolumetricFlux (phi)
if()
if (args. found"fluxCorrection")
setVelocity()
velocityModel setVelocity (U)
Variable Documentation
redist
Info<< "Reading field psi\n" << endl;volScalarField psi (IOobject ("psi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field alpha\n" << endl;volScalarField alpha(IOobject ("alpha", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field phi\n" << endl;surfaceScalarField phi (IOobject ("phi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar ("phi", dimVolume / dimTime, 0));Info<< "Initializing field U (visualization)\n" << endl;volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector("U", dimVelocity, vector(0,0,0)));autoPtr<redistancer> redist = redistancer::New(mesh)
Definition at line 65 of file createFields.H.
Referenced by main(), and redistancedPlaneIsUnchanged().
narrowBand
autoPtr<NarrowBand> narrowBand = NarrowBand::New(mesh, psi)
Definition at line 68 of file createFields.H.
Referenced by geometricPhaseIndicator::calcPhaseIndicator(), and gradPsiErrorCSV::write().
phaseInd
autoPtr<phaseIndicator> phaseInd = phaseIndicator::New(mesh)
Definition at line 73 of file createFields.H.
Referenced by main(), and phaseIndicatorIsBounded().
source
autoPtr<SDPLSSource> source = SDPLSSource::New(mesh)
Definition at line 78 of file createFields.H.
Referenced by geometricPhaseIndicator::calcPhaseIndicator().
velocityModel
autoPtr<velocityModel> velocityModel = velocityModel::New(mesh)
Definition at line 83 of file createFields.H.