LEIA: /home/julian/OpenFOAM/leia2/applications/solvers/leiaLevelSetFoam/errorCalculation.H File Reference
errorCalculation.H File Reference
Functions
surfaceScalarField phi0 ("phi0", phi)
volVectorField U0 ("U0", U)
volScalarField psi0 (IOobject("psiEnd", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), psi)
volScalarField alpha0 (IOobject("alphaEnd", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), alpha)
OFstream errorFile ("leiaLevelSetFoam.csv")
Function Documentation
phi0()
surfaceScalarField phi0 ("phi0" , phi)
Referenced by velocityModel::oscillateVelocity().
U0()
volVectorField U0 ("U0" , U)
Referenced by velocityModel::oscillateVelocity().
psi0()
volScalarField psi0 (IOobject("psiEnd", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE) , psi)
Referenced by redistancedPlaneIsUnchanged(), and reportErrors().
alpha0()
volScalarField alpha0 (IOobject("alphaEnd", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE) , alpha)
Referenced by reportErrors().
errorFile()
OFstream errorFile ("leiaLevelSetFoam.csv")