LEIA: SignChangeNarrowBand Class Reference
SignChangeNarrowBand Class Reference
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
Public Member Functions
TypeName ("signChange")
SignChangeNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~SignChangeNarrowBand ()=default
virtual void calc ()
Public Member Functions inherited from EmptyNarrowBand
TypeName ("empty")
EmptyNarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~EmptyNarrowBand ()=default
const volScalarField & field () const
volScalarField & field ()
virtual void write () const
Public Member Functions inherited from NarrowBand
TypeName ("none")
declareRunTimeSelectionTable (autoPtr, NarrowBand, Dictionary,(const dictionary &dict, const volScalarField &psi),(dict, psi))
NarrowBand (const dictionary &dict, const volScalarField &psi)
virtual ~NarrowBand ()=default
const fvMesh & mesh () const
const volScalarField & psi () const
Additional Inherited Members
Static Public Member Functions inherited from NarrowBand
static autoPtr< NarrowBand > New (const fvMesh &mesh, const volScalarField &psi)
Protected Attributes inherited from NarrowBand
const fvMesh & mesh_
const volScalarField & psi_
Detailed Description
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
Source files
SignChangeNarrowBand.H
SignChangeNarrowBand.C
Definition at line 48 of file SignChangeNarrowBand.H.
Constructor & Destructor Documentation
SignChangeNarrowBand()
SignChangeNarrowBand (const dictionary & dict, const volScalarField & psi)
Definition at line 30 of file SignChangeNarrowBand.C.
~SignChangeNarrowBand()
virtual ~SignChangeNarrowBand () virtual default
Member Function Documentation
TypeName()
TypeName ("signChange")
calc()
void calc () virtual
Reimplemented from NarrowBand.
Reimplemented in NeighbourNarrowBand.
Definition at line 35 of file SignChangeNarrowBand.C.
References EmptyNarrowBand::field(), NarrowBand::mesh(), and NarrowBand::psi().
Referenced by NeighbourNarrowBand::calc().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/SignChangeNarrowBand.H
/home/julian/OpenFOAM/leia2/src/leiaLevelSet/NarrowBand/SignChangeNarrowBand.C