LEIA: explicitGradientFvPatchField Class Reference
explicitGradientFvPatchField Class Reference
Sets the BC gradient to the gradient of the internalField of the last time step.
Public Member Functions
TypeName ("explicitGradient")
Runtime type information.
explicitGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
explicitGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
explicitGradientFvPatchField (const explicitGradientFvPatchField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given explicitGradientFvPatchField.
explicitGradientFvPatchField (const explicitGradientFvPatchField &)
Construct as copy.
virtual tmp< fvPatchField< scalar > > clone () const
Construct and return a clone.
explicitGradientFvPatchField (const explicitGradientFvPatchField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< Field< scalar > > snGrad () const
Return gradient at boundary.
virtual tmp< Field< vector > > calcGradient ()
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Evaluate the patch field.
virtual void write (Ostream &os) const
Private Attributes
Field< scalar > snGrad_
Detailed Description
Sets the BC gradient to the gradient of the internalField of the last time step.
$\nabla \psi_b^{n+1} = \nabla \psi_c^{n} $
where
= gradient (user-specified)
Usage
Example of the boundary condition specification:
<patchName>
{
    type            explicitGradient;
}
Source files
explicitGradientFvPatchField.H
explicitGradientFvPatchField.C
Definition at line 72 of file explicitGradientFvPatchField.H.
Constructor & Destructor Documentation
explicitGradientFvPatchField() [1/5]
explicitGradientFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 31 of file explicitGradientFvPatchField.C.
Referenced by explicitGradientFvPatchField::clone().
explicitGradientFvPatchField() [2/5]
explicitGradientFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 55 of file explicitGradientFvPatchField.C.
References explicitGradientFvPatchField::snGrad_.
explicitGradientFvPatchField() [3/5]
explicitGradientFvPatchField (const explicitGradientFvPatchField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given explicitGradientFvPatchField.
onto a new patch
Definition at line 73 of file explicitGradientFvPatchField.C.
explicitGradientFvPatchField() [4/5]
explicitGradientFvPatchField (const explicitGradientFvPatchField & ptf)
Construct as copy.
Definition at line 97 of file explicitGradientFvPatchField.C.
explicitGradientFvPatchField() [5/5]
explicitGradientFvPatchField (const explicitGradientFvPatchField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 109 of file explicitGradientFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("explicitGradient")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchField<scalar> > clone () const inline virtual
Construct and return a clone.
Reimplemented in explicitMag1GradientFvPatchField.
Definition at line 140 of file explicitGradientFvPatchField.H.
References explicitGradientFvPatchField::explicitGradientFvPatchField().
clone() [2/2]
virtual tmp<fvPatchField<scalar> > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in explicitMag1GradientFvPatchField.
Definition at line 160 of file explicitGradientFvPatchField.H.
References explicitGradientFvPatchField::explicitGradientFvPatchField().
snGrad()
Foam::tmp< Foam::Field< scalar > > snGrad () const virtual
Return gradient at boundary.
Definition at line 132 of file explicitGradientFvPatchField.C.
calcGradient()
tmp< Field< vector > > calcGradient () virtual
Reimplemented in explicitMag1GradientFvPatchField.
Definition at line 124 of file explicitGradientFvPatchField.C.
Referenced by explicitMag1GradientFvPatchField::calcGradient().
valueInternalCoeffs()
Foam::tmp< Foam::Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 158 of file explicitGradientFvPatchField.C.
valueBoundaryCoeffs()
Foam::tmp< Foam::Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Return the matrix source coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 172 of file explicitGradientFvPatchField.C.
gradientInternalCoeffs()
Foam::tmp< Foam::Field< scalar > > gradientInternalCoeffs () const virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this patchField
Definition at line 183 of file explicitGradientFvPatchField.C.
gradientBoundaryCoeffs()
Foam::tmp< Foam::Field< scalar > > gradientBoundaryCoeffs () const virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this patchField
Definition at line 194 of file explicitGradientFvPatchField.C.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Evaluate the patch field.
Definition at line 138 of file explicitGradientFvPatchField.C.
write()
void write (Ostream & os) const virtual
Definition at line 199 of file explicitGradientFvPatchField.C.
References write().
Member Data Documentation
snGrad_
Field<scalar> snGrad_ private
Definition at line 77 of file explicitGradientFvPatchField.H.
Referenced by explicitGradientFvPatchField::explicitGradientFvPatchField().
The documentation for this class was generated from the following files:
/home/julian/OpenFOAM/leia2/src/finiteVolume/fields/fvPatchFields/derived/explicitGradient/explicitGradientFvPatchField.H
/home/julian/OpenFOAM/leia2/src/finiteVolume/fields/fvPatchFields/derived/explicitGradient/explicitGradientFvPatchField.C