LEIA: velocityModel Class Reference
velocityModel Class Reference
Public Member Functions
TypeName ("none")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, velocityModel, Mesh,(const fvMesh &mesh),(mesh))
velocityModel (const fvMesh &mesh)
virtual ~velocityModel ()=default
Switch isOscillating () const
scalar oscillationFactor (scalar const time, const scalar tau) const
void oscillateVelocity (volVectorField &U, const volVectorField &U0, surfaceScalarField &phi, const surfaceScalarField &phi0, const Time &runTime) const
virtual Foam::vector velocity (const vector &x) const
virtual void setVelocity (volVectorField &U) const
virtual void setVolumetricFlux (surfaceScalarField &phi) const
Static Public Member Functions
static autoPtr< velocityModel > New (const fvMesh &mesh)
Return a reference to the selected viscosity model.
Protected Attributes
const fvSolution & fvSolution_
const dictionary & velocityDict_
Switch isOscillating_
const scalar tau_
Detailed Description
Definition at line 49 of file advectionVerification.H.
Constructor & Destructor Documentation
velocityModel()
velocityModel (const fvMesh & mesh) inline
Definition at line 84 of file advectionVerification.H.
~velocityModel()
virtual ~velocityModel () virtual default
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , velocityModel , Mesh , (const fvMesh &mesh) , (mesh))
New()
autoPtr< velocityModel > New (const fvMesh & mesh) static
Return a reference to the selected viscosity model.
Definition at line 204 of file advectionVerification.H.
isOscillating()
Switch isOscillating () const inline
Definition at line 108 of file advectionVerification.H.
References velocityModel::isOscillating_.
Referenced by velocityModel::oscillateVelocity().
oscillationFactor()
scalar oscillationFactor (scalar const time, const scalar tau) const inline
Definition at line 113 of file advectionVerification.H.
Referenced by velocityModel::oscillateVelocity().
oscillateVelocity()
void oscillateVelocity (volVectorField & U, const volVectorField & U0, surfaceScalarField & phi, const surfaceScalarField & phi0, const Time & runTime) const inline
Definition at line 118 of file advectionVerification.H.
References velocityModel::isOscillating(), velocityModel::oscillationFactor(), phi0(), velocityModel::tau_, and U0().
velocity()
virtual Foam::vector velocity (const vector & x) const inline virtual
Reimplemented in periodic2D, vortex2D, rotation, translation, shear3D, deformation3D, and shear2D.
Definition at line 135 of file advectionVerification.H.
Referenced by velocityModel::setVelocity(), and velocityModel::setVolumetricFlux().
setVelocity()
virtual void setVelocity (volVectorField & U) const inline virtual
Definition at line 141 of file advectionVerification.H.
References velocityModel::velocity().
setVolumetricFlux()
virtual void setVolumetricFlux (surfaceScalarField & phi) const inline virtual
Definition at line 167 of file advectionVerification.H.
References velocityModel::velocity().
Member Data Documentation
fvSolution_
const fvSolution& fvSolution_ protected
Definition at line 53 of file advectionVerification.H.
velocityDict_
const dictionary& velocityDict_ protected
Definition at line 54 of file advectionVerification.H.
isOscillating_
Switch isOscillating_ protected
Definition at line 55 of file advectionVerification.H.
Referenced by velocityModel::isOscillating().
tau_
const scalar tau_ protected
Definition at line 56 of file advectionVerification.H.
Referenced by velocityModel::oscillateVelocity().
The documentation for this class was generated from the following file:
/home/julian/OpenFOAM/leia2/applications/solvers/leiaLevelSetFoam/advectionVerification.H