LEIA: Foam Namespace Reference
Foam Namespace Reference
Namespaces
functionObjects
fvm
Classes
class explicitGradientFvPatchField
Sets the BC gradient to the gradient of the internalField of the last time step.
class explicitMag1GradientFvPatchField
Sets the BC gradient to the normalized gradient of the internalField of the last time step.
class writeIsoSurfaceTopoFunctionObject
class DistanceNarrowBand
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
class EmptyNarrowBand
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
class NarrowBand
Abstract base class which starts the model hierachy for marking cells which are near the interface aka the "narrowBand". Calculate a field with {0,1} which mark cells near the zero level-set interface.
class NeighbourNarrowBand
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
class SignChangeNarrowBand
Concrete class which calculates a field with {0,1} which mark cells near the zero level-set interface.
class geometricPhaseIndicator
Computes the phase indicator as a volume fraction from a field \psi_c.
class heavisidePhaseIndicator
class phaseIndicator
class sharpJumpPhaseIndicator
class profile
Abstract base class which starts the hierachy for different level-set profile fields, typically signedDistance or tanh variants.
class signedDistance
Concrete class which represents the model for signedDistance.
class tanhProfile
class lsqRedistancer
class redistancer
class GradPsi
class NarrowLS
class Mollifier
class Mollifier1
class SDPLS_lin
Concrete class which calculates the SDPLS source term explicitly.
class SDPLS_quad
Concrete class which calculates the SDPLS source term explicitly.
class SDPLS_R
Concrete class which calculates the SDPLS source term explicitly.
class SDPLS_Rlin
Concrete class which calculates the SDPLS source term explicitly.
class SDPLS_Rquad
Concrete class which calculates the SDPLS source term explicitly.
class SDPLSSource
The base class SDPLSSource is the root for the model hierarchy of the SDPLS method by Fricke et. al. [1]. It is the only class with which the user of the SDPLS method should interact. The SDPLS method extends the standard LS advection equation with the SDPLS source term. This is done by extending the r.h.s. of the LS equation in the solver application by calling.
class explicitScheme
The class explicitScheme implements the explicit discretization of the source term.
class simpleLinearImplicitScheme
The class simpleLinearImplicitScheme implements an implicit discretization of the source term in the most simplest way.
class SourceScheme
The base class SourceScheme forms the root for the discretization hierarchy of the SDPLS source term implemented in SDPLSSource.
class strictNegativeSpLinearImplicitScheme
The class strictNegativeSpLinearImplicitScheme implements an implicit discretization of the source term that ensures contributions to the diagonal dominance of the resulting algebraic linear system.
class implicitSurface
class implicitPlane
class hesseNormalPlane
class implicitSphere
class implicitSlottedSphere
class implicitEllipsoid
class implicitSinc
struct volumeArea
class velocityModel
class shear2D
class deformation3D
class shear3D
class translation
class rotation
class vortex2D
class periodic2D
Functions
makePatchTypeField (fvPatchScalarField, explicitGradientFvPatchField)
makePatchTypeField (fvPatchScalarField, explicitMag1GradientFvPatchField)
defineTypeNameAndDebug (writeIsoSurfaceTopoFunctionObject, 0)
addRemovableToRunTimeSelectionTable (functionObject, writeIsoSurfaceTopoFunctionObject, dictionary)
void writeIsoSurfaceTopo (const fvMesh &mesh, bool forceWrite)
defineTypeNameAndDebug (DistanceNarrowBand, false)
addToRunTimeSelectionTable (NarrowBand, DistanceNarrowBand, Dictionary)
defineTypeNameAndDebug (EmptyNarrowBand, false)
addToRunTimeSelectionTable (NarrowBand, EmptyNarrowBand, Dictionary)
defineTypeNameAndDebug (NarrowBand, false)
defineRunTimeSelectionTable (NarrowBand, Dictionary)
addToRunTimeSelectionTable (NarrowBand, NarrowBand, Dictionary)
defineTypeNameAndDebug (NeighbourNarrowBand, false)
addToRunTimeSelectionTable (NarrowBand, NeighbourNarrowBand, Dictionary)
defineTypeNameAndDebug (SignChangeNarrowBand, false)
addToRunTimeSelectionTable (NarrowBand, SignChangeNarrowBand, Dictionary)
defineTypeNameAndDebug (geometricPhaseIndicator, false)
addToRunTimeSelectionTable (phaseIndicator, geometricPhaseIndicator, Mesh)
defineTypeNameAndDebug (heavisidePhaseIndicator, false)
addToRunTimeSelectionTable (phaseIndicator, heavisidePhaseIndicator, Mesh)
defineTypeNameAndDebug (phaseIndicator, false)
defineRunTimeSelectionTable (phaseIndicator, Mesh)
defineTypeNameAndDebug (sharpJumpPhaseIndicator, false)
addToRunTimeSelectionTable (phaseIndicator, sharpJumpPhaseIndicator, Mesh)
defineTypeNameAndDebug (profile, false)
defineRunTimeSelectionTable (profile, Mesh)
defineTypeNameAndDebug (signedDistance, false)
addToRunTimeSelectionTable (profile, signedDistance, Mesh)
defineTypeNameAndDebug (tanhProfile, false)
addToRunTimeSelectionTable (profile, tanhProfile, Mesh)
defineTypeNameAndDebug (lsqRedistancer, false)
addToRunTimeSelectionTable (redistancer, lsqRedistancer, Mesh)
defineTypeNameAndDebug (redistancer, false)
defineRunTimeSelectionTable (redistancer, Mesh)
addToRunTimeSelectionTable (redistancer, redistancer, Mesh)
defineTypeNameAndDebug (GradPsi, false)
defineRunTimeSelectionTable (GradPsi, Dictionary)
addToRunTimeSelectionTable (GradPsi, GradPsi, Dictionary)
defineTypeNameAndDebug (NarrowLS, false)
addToRunTimeSelectionTable (GradPsi, NarrowLS, Dictionary)
defineTypeNameAndDebug (Mollifier, false)
defineRunTimeSelectionTable (Mollifier, Dictionary)
addToRunTimeSelectionTable (Mollifier, Mollifier, Dictionary)
defineTypeNameAndDebug (Mollifier1, false)
addToRunTimeSelectionTable (Mollifier, Mollifier1, Dictionary)
defineTypeNameAndDebug (SDPLS_lin, false)
addToRunTimeSelectionTable (SDPLSSource, SDPLS_lin, Dictionary)
defineTypeNameAndDebug (SDPLS_quad, false)
addToRunTimeSelectionTable (SDPLSSource, SDPLS_quad, Dictionary)
defineTypeNameAndDebug (SDPLS_R, false)
addToRunTimeSelectionTable (SDPLSSource, SDPLS_R, Dictionary)
defineTypeNameAndDebug (SDPLS_Rlin, false)
addToRunTimeSelectionTable (SDPLSSource, SDPLS_Rlin, Dictionary)
defineTypeNameAndDebug (SDPLS_Rquad, false)
addToRunTimeSelectionTable (SDPLSSource, SDPLS_Rquad, Dictionary)
defineTypeNameAndDebug (SDPLSSource, false)
defineRunTimeSelectionTable (SDPLSSource, Dictionary)
addToRunTimeSelectionTable (SDPLSSource, SDPLSSource, Dictionary)
defineTypeNameAndDebug (explicitScheme, false)
addToRunTimeSelectionTable (SourceScheme, explicitScheme, Dictionary)
defineTypeNameAndDebug (simpleLinearImplicitScheme, false)
addToRunTimeSelectionTable (SourceScheme, simpleLinearImplicitScheme, Dictionary)
defineTypeNameAndDebug (SourceScheme, false)
defineRunTimeSelectionTable (SourceScheme, Dictionary)
addToRunTimeSelectionTable (SourceScheme, SourceScheme, Dictionary)
defineTypeNameAndDebug (strictNegativeSpLinearImplicitScheme, false)
addToRunTimeSelectionTable (SourceScheme, strictNegativeSpLinearImplicitScheme, Dictionary)
defineTypeNameAndDebug (implicitSurface, false)
defineRunTimeSelectionTable (implicitSurface, dictionary)
defineTypeNameAndDebug (implicitPlane, false)
addToRunTimeSelectionTable (implicitSurface, implicitPlane, dictionary)
defineTypeNameAndDebug (hesseNormalPlane, false)
addToRunTimeSelectionTable (implicitSurface, hesseNormalPlane, dictionary)
defineTypeNameAndDebug (implicitSphere, false)
addToRunTimeSelectionTable (implicitSurface, implicitSphere, dictionary)
defineTypeNameAndDebug (implicitSlottedSphere, false)
addToRunTimeSelectionTable (implicitSurface, implicitSlottedSphere, dictionary)
defineTypeNameAndDebug (implicitEllipsoid, false)
addToRunTimeSelectionTable (implicitSurface, implicitEllipsoid, dictionary)
defineTypeNameAndDebug (implicitSinc, false)
addToRunTimeSelectionTable (implicitSurface, implicitSinc, dictionary)
template<typename PointSequence >
scalar normalArea (PointSequence const &points, const vector &normal)
template<typename PointSequence >
point centroid (PointSequence const &points)
template<typename PointSequence >
vector centroidAreaNormal (PointSequence const &points, const point &centroid)
template<typename OrientedPointSequence >
vector orientedAreaNormal (OrientedPointSequence const &points)
template<typename Intersection = volumeArea, typename ImplicitPlane >
Intersection intersectCell (label cellL, const fvMesh &mesh, ImplicitPlane plane)
defineTypeNameAndDebug (velocityModel, 0)
defineRunTimeSelectionTable (velocityModel, Mesh)
defineTypeNameAndDebug (deformation3D, 0)
addToRunTimeSelectionTable (velocityModel, deformation3D, Mesh)
defineTypeNameAndDebug (shear3D, 0)
addToRunTimeSelectionTable (velocityModel, shear3D, Mesh)
defineTypeNameAndDebug (translation, 0)
addToRunTimeSelectionTable (velocityModel, translation, Mesh)
defineTypeNameAndDebug (rotation, 0)
addToRunTimeSelectionTable (velocityModel, rotation, Mesh)
defineTypeNameAndDebug (vortex2D, 0)
addToRunTimeSelectionTable (velocityModel, vortex2D, Mesh)
defineTypeNameAndDebug (periodic2D, 0)
addToRunTimeSelectionTable (velocityModel, periodic2D, Mesh)
void correctFlux (surfaceScalarField &phi)
Detailed Description
,
for a polyedral finite volume cell \Omega_c, using the divergence theorem in 3D (volume), then again in 2D (area).
Function Documentation
makePatchTypeField() [1/2]
Foam::makePatchTypeField (fvPatchScalarField , explicitGradientFvPatchField)
makePatchTypeField() [2/2]
Foam::makePatchTypeField (fvPatchScalarField , explicitMag1GradientFvPatchField)
defineTypeNameAndDebug() [1/43]
Foam::defineTypeNameAndDebug (writeIsoSurfaceTopoFunctionObject , 0)
addRemovableToRunTimeSelectionTable()
Foam::addRemovableToRunTimeSelectionTable (functionObject , writeIsoSurfaceTopoFunctionObject , dictionary)
writeIsoSurfaceTopo()
void Foam::writeIsoSurfaceTopo (const fvMesh & mesh, bool forceWrite)
Definition at line 46 of file writeIsoSurfaceTopo.H.
Referenced by writeIsoSurfaceTopoFunctionObject::end(), writeIsoSurfaceTopoFunctionObject::execute(), and writeIsoSurfaceTopoFunctionObject::read().
defineTypeNameAndDebug() [2/43]
Foam::defineTypeNameAndDebug (DistanceNarrowBand , false)
addToRunTimeSelectionTable() [1/38]
Foam::addToRunTimeSelectionTable (NarrowBand , DistanceNarrowBand , Dictionary)
defineTypeNameAndDebug() [3/43]
Foam::defineTypeNameAndDebug (EmptyNarrowBand , false)
addToRunTimeSelectionTable() [2/38]
Foam::addToRunTimeSelectionTable (NarrowBand , EmptyNarrowBand , Dictionary)
defineTypeNameAndDebug() [4/43]
Foam::defineTypeNameAndDebug (NarrowBand , false)
defineRunTimeSelectionTable() [1/10]
Foam::defineRunTimeSelectionTable (NarrowBand , Dictionary)
addToRunTimeSelectionTable() [3/38]
Foam::addToRunTimeSelectionTable (NarrowBand , NarrowBand , Dictionary)
defineTypeNameAndDebug() [5/43]
Foam::defineTypeNameAndDebug (NeighbourNarrowBand , false)
addToRunTimeSelectionTable() [4/38]
Foam::addToRunTimeSelectionTable (NarrowBand , NeighbourNarrowBand , Dictionary)
defineTypeNameAndDebug() [6/43]
Foam::defineTypeNameAndDebug (SignChangeNarrowBand , false)
addToRunTimeSelectionTable() [5/38]
Foam::addToRunTimeSelectionTable (NarrowBand , SignChangeNarrowBand , Dictionary)
defineTypeNameAndDebug() [7/43]
Foam::defineTypeNameAndDebug (geometricPhaseIndicator , false)
addToRunTimeSelectionTable() [6/38]
Foam::addToRunTimeSelectionTable (phaseIndicator , geometricPhaseIndicator , Mesh)
defineTypeNameAndDebug() [8/43]
Foam::defineTypeNameAndDebug (heavisidePhaseIndicator , false)
addToRunTimeSelectionTable() [7/38]
Foam::addToRunTimeSelectionTable (phaseIndicator , heavisidePhaseIndicator , Mesh)
defineTypeNameAndDebug() [9/43]
Foam::defineTypeNameAndDebug (phaseIndicator , false)
defineRunTimeSelectionTable() [2/10]
Foam::defineRunTimeSelectionTable (phaseIndicator , Mesh)
defineTypeNameAndDebug() [10/43]
Foam::defineTypeNameAndDebug (sharpJumpPhaseIndicator , false)
addToRunTimeSelectionTable() [8/38]
Foam::addToRunTimeSelectionTable (phaseIndicator , sharpJumpPhaseIndicator , Mesh)
defineTypeNameAndDebug() [11/43]
Foam::defineTypeNameAndDebug (profile , false)
defineRunTimeSelectionTable() [3/10]
Foam::defineRunTimeSelectionTable (profile , Mesh)
defineTypeNameAndDebug() [12/43]
Foam::defineTypeNameAndDebug (signedDistance , false)
addToRunTimeSelectionTable() [9/38]
Foam::addToRunTimeSelectionTable (profile , signedDistance , Mesh)
defineTypeNameAndDebug() [13/43]
Foam::defineTypeNameAndDebug (tanhProfile , false)
addToRunTimeSelectionTable() [10/38]
Foam::addToRunTimeSelectionTable (profile , tanhProfile , Mesh)
defineTypeNameAndDebug() [14/43]
Foam::defineTypeNameAndDebug (lsqRedistancer , false)
addToRunTimeSelectionTable() [11/38]
Foam::addToRunTimeSelectionTable (redistancer , lsqRedistancer , Mesh)
defineTypeNameAndDebug() [15/43]
Foam::defineTypeNameAndDebug (redistancer , false)
defineRunTimeSelectionTable() [4/10]
Foam::defineRunTimeSelectionTable (redistancer , Mesh)
addToRunTimeSelectionTable() [12/38]
Foam::addToRunTimeSelectionTable (redistancer , redistancer , Mesh)
defineTypeNameAndDebug() [16/43]
Foam::defineTypeNameAndDebug (GradPsi , false)
defineRunTimeSelectionTable() [5/10]
Foam::defineRunTimeSelectionTable (GradPsi , Dictionary)
addToRunTimeSelectionTable() [13/38]
Foam::addToRunTimeSelectionTable (GradPsi , GradPsi , Dictionary)
defineTypeNameAndDebug() [17/43]
Foam::defineTypeNameAndDebug (NarrowLS , false)
addToRunTimeSelectionTable() [14/38]
Foam::addToRunTimeSelectionTable (GradPsi , NarrowLS , Dictionary)
defineTypeNameAndDebug() [18/43]
Foam::defineTypeNameAndDebug (Mollifier , false)
defineRunTimeSelectionTable() [6/10]
Foam::defineRunTimeSelectionTable (Mollifier , Dictionary)
addToRunTimeSelectionTable() [15/38]
Foam::addToRunTimeSelectionTable (Mollifier , Mollifier , Dictionary)
defineTypeNameAndDebug() [19/43]
Foam::defineTypeNameAndDebug (Mollifier1 , false)
addToRunTimeSelectionTable() [16/38]
Foam::addToRunTimeSelectionTable (Mollifier , Mollifier1 , Dictionary)
defineTypeNameAndDebug() [20/43]
Foam::defineTypeNameAndDebug (SDPLS_lin , false)
addToRunTimeSelectionTable() [17/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLS_lin , Dictionary)
defineTypeNameAndDebug() [21/43]
Foam::defineTypeNameAndDebug (SDPLS_quad , false)
addToRunTimeSelectionTable() [18/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLS_quad , Dictionary)
defineTypeNameAndDebug() [22/43]
Foam::defineTypeNameAndDebug (SDPLS_R , false)
addToRunTimeSelectionTable() [19/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLS_R , Dictionary)
defineTypeNameAndDebug() [23/43]
Foam::defineTypeNameAndDebug (SDPLS_Rlin , false)
addToRunTimeSelectionTable() [20/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLS_Rlin , Dictionary)
defineTypeNameAndDebug() [24/43]
Foam::defineTypeNameAndDebug (SDPLS_Rquad , false)
addToRunTimeSelectionTable() [21/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLS_Rquad , Dictionary)
defineTypeNameAndDebug() [25/43]
Foam::defineTypeNameAndDebug (SDPLSSource , false)
defineRunTimeSelectionTable() [7/10]
Foam::defineRunTimeSelectionTable (SDPLSSource , Dictionary)
addToRunTimeSelectionTable() [22/38]
Foam::addToRunTimeSelectionTable (SDPLSSource , SDPLSSource , Dictionary)
defineTypeNameAndDebug() [26/43]
Foam::defineTypeNameAndDebug (explicitScheme , false)
addToRunTimeSelectionTable() [23/38]
Foam::addToRunTimeSelectionTable (SourceScheme , explicitScheme , Dictionary)
defineTypeNameAndDebug() [27/43]
Foam::defineTypeNameAndDebug (simpleLinearImplicitScheme , false)
addToRunTimeSelectionTable() [24/38]
Foam::addToRunTimeSelectionTable (SourceScheme , simpleLinearImplicitScheme , Dictionary)
defineTypeNameAndDebug() [28/43]
Foam::defineTypeNameAndDebug (SourceScheme , false)
defineRunTimeSelectionTable() [8/10]
Foam::defineRunTimeSelectionTable (SourceScheme , Dictionary)
addToRunTimeSelectionTable() [25/38]
Foam::addToRunTimeSelectionTable (SourceScheme , SourceScheme , Dictionary)
defineTypeNameAndDebug() [29/43]
Foam::defineTypeNameAndDebug (strictNegativeSpLinearImplicitScheme , false)
addToRunTimeSelectionTable() [26/38]
Foam::addToRunTimeSelectionTable (SourceScheme , strictNegativeSpLinearImplicitScheme , Dictionary)
defineTypeNameAndDebug() [30/43]
Foam::defineTypeNameAndDebug (implicitSurface , false)
defineRunTimeSelectionTable() [9/10]
Foam::defineRunTimeSelectionTable (implicitSurface , dictionary)
defineTypeNameAndDebug() [31/43]
Foam::defineTypeNameAndDebug (implicitPlane , false)
addToRunTimeSelectionTable() [27/38]
Foam::addToRunTimeSelectionTable (implicitSurface , implicitPlane , dictionary)
defineTypeNameAndDebug() [32/43]
Foam::defineTypeNameAndDebug (hesseNormalPlane , false)
addToRunTimeSelectionTable() [28/38]
Foam::addToRunTimeSelectionTable (implicitSurface , hesseNormalPlane , dictionary)
defineTypeNameAndDebug() [33/43]
Foam::defineTypeNameAndDebug (implicitSphere , false)
addToRunTimeSelectionTable() [29/38]
Foam::addToRunTimeSelectionTable (implicitSurface , implicitSphere , dictionary)
defineTypeNameAndDebug() [34/43]
Foam::defineTypeNameAndDebug (implicitSlottedSphere , false)
addToRunTimeSelectionTable() [30/38]
Foam::addToRunTimeSelectionTable (implicitSurface , implicitSlottedSphere , dictionary)
defineTypeNameAndDebug() [35/43]
Foam::defineTypeNameAndDebug (implicitEllipsoid , false)
addToRunTimeSelectionTable() [31/38]
Foam::addToRunTimeSelectionTable (implicitSurface , implicitEllipsoid , dictionary)
defineTypeNameAndDebug() [36/43]
Foam::defineTypeNameAndDebug (implicitSinc , false)
addToRunTimeSelectionTable() [32/38]
Foam::addToRunTimeSelectionTable (implicitSurface , implicitSinc , dictionary)
normalArea()
scalar Foam::normalArea (PointSequence const & points, const vector & normal)
Definition at line 57 of file foamGeometry.H.
Referenced by testOrientedSquareArea(), testTriangleArea(), and testUnorientedSquareArea().
centroid()
point Foam::centroid (PointSequence const & points)
Definition at line 82 of file foamGeometry.H.
Referenced by centroidAreaNormal(), testOrientedSquareArea(), testTriangleArea(), and testUnorientedSquareArea().
centroidAreaNormal()
vector Foam::centroidAreaNormal (PointSequence const & points, const point & centroid)
Definition at line 94 of file foamGeometry.H.
References centroid().
Referenced by testOrientedSquareArea(), testTriangleArea(), and testUnorientedSquareArea().
orientedAreaNormal()
vector Foam::orientedAreaNormal (OrientedPointSequence const & points)
Definition at line 114 of file foamGeometry.H.
Referenced by intersectCell(), testOrientedSquareArea(), and testTriangleArea().
intersectCell()
Intersection Foam::intersectCell (label cellL, const fvMesh & mesh, ImplicitPlane plane)
Definition at line 154 of file foamGeometry.H.
References orientedAreaNormal().
Referenced by geometricPhaseIndicator::calcPhaseIndicator(), testVolFraction_UnitDomainHalved(), testVolFraction_UnitDomainInsidePlaneHalfspace(), and testVolFraction_UnitDomainTranslatingPlane().
defineTypeNameAndDebug() [37/43]
Foam::defineTypeNameAndDebug (velocityModel , 0)
defineRunTimeSelectionTable() [10/10]
Foam::defineRunTimeSelectionTable (velocityModel , Mesh)
defineTypeNameAndDebug() [38/43]
Foam::defineTypeNameAndDebug (deformation3D , 0)
addToRunTimeSelectionTable() [33/38]
Foam::addToRunTimeSelectionTable (velocityModel , deformation3D , Mesh)
defineTypeNameAndDebug() [39/43]
Foam::defineTypeNameAndDebug (shear3D , 0)
addToRunTimeSelectionTable() [34/38]
Foam::addToRunTimeSelectionTable (velocityModel , shear3D , Mesh)
defineTypeNameAndDebug() [40/43]
Foam::defineTypeNameAndDebug (translation , 0)
addToRunTimeSelectionTable() [35/38]
Foam::addToRunTimeSelectionTable (velocityModel , translation , Mesh)
defineTypeNameAndDebug() [41/43]
Foam::defineTypeNameAndDebug (rotation , 0)
addToRunTimeSelectionTable() [36/38]
Foam::addToRunTimeSelectionTable (velocityModel , rotation , Mesh)
defineTypeNameAndDebug() [42/43]
Foam::defineTypeNameAndDebug (vortex2D , 0)
addToRunTimeSelectionTable() [37/38]
Foam::addToRunTimeSelectionTable (velocityModel , vortex2D , Mesh)
defineTypeNameAndDebug() [43/43]
Foam::defineTypeNameAndDebug (periodic2D , 0)
addToRunTimeSelectionTable() [38/38]
Foam::addToRunTimeSelectionTable (velocityModel , periodic2D , Mesh)
correctFlux()
void Foam::correctFlux (surfaceScalarField & phi)
Definition at line 470 of file advectionVerification.H.